### ISSUE TITLE
Get camera feed

### ISSUE THREAD

**Issue by GUnoahj** [DIT113-V22/group-09#15] opened 2022-04-01 14:46 UTC
As a user I want to steer my car wirelessly so that I can control the vehicle remotely.

Acceptance Criteria:

- [ ] The user is able to receive real-time video feed from the camera device attached to the vehicle.
- [ ] The implementation is tested.

**Comment by Peym77** [comment] 2022-04-14 19:05
duplicate of #17

**Closed as completed by Peym77** 2022-04-14 19:05 UTC
Labels: duplicate
